# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9ba7aa28c15a62e886949fb87534e80baf2f1f96d6f311e78eb1ae21c33821e5e5b2e2c91600c40a4cf85bdb6c52e1b72d5cdc41670d1e739a4e676c4297e64

test:
  secret_key_base: 19cbca3ea80941d29f4265145bf1d3ec4c1d54d7cd34f956dbefd028b07b6af7c39c127be92dc2038f3a4816980e255e54cfc300386d7911d2c6f15b2db1e74f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
